language: python
services:
  - postgresql
addons:
  postgresql: "9.4"
python:
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxmlsec1-dev
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - DJANGO_SETTINGS_MODULE=idm_auth.tests.settings DJANGO_ALLOWED_HOSTS=localhost DJANGO_SECRET_KEY=secret-key-for-travis
script: PYTHONPATH=. coverage run --source=. `which django-admin.py` test
after_success:
  - codecov
